# Generated by Django 4.2 on 2023-04-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mentoring", "0001_initial"),
    ]

    operations = []
