# Generated by Django 4.2 on 2023-04-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mentoring", "0005_mentorshiprequest_description_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
