# Generated by Django 4.2 on 2023-04-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_login", "0002_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
